### ISSUE TITLE
Unknown launch failure

### ISSUE THREAD

**Issue by mworzala** [mworzala/mc-cli#15]
OS: arch linux, x86

```
panic: exit status 1

goroutine 1 [running]:
github.com/mworzala/mc/internal/pkg/game/launch.LaunchProfile({0xc0000e8840, 0x22}, 0xc0000b30c0, 0xc00023e240, {0xc0002a4000, 0x234}, 0xc000024340, 0x1)
    /home/.../go/pkg/mod/github.com/mworzala/mc@v0.1.1/internal/pkg/game/launch/launch.go:226 +0x1f30
github.com/mworzala/mc/cmd/mc.(*launchOpts).launch(0xc0000b0c20, {0xc0000eed40, 0x1, 0x0?})
    /home/.../go/pkg/mod/github.com/mworzala/mc@v0.1.1/cmd/mc/launch.go:74 +0x2bf
github.com/mworzala/mc/cmd/mc.newLaunchCmd.func1(0xc00014a800?, {0xc0000eed40?, 0x4?, 0x8e168c?})
    /home/.../go/pkg/mod/github.com/mworzala/mc@v0.1.1/cmd/mc/launch.go:31 +0x3b
github.com/spf13/cobra.(*Command).execute(0xc000184300, {0xc0000eed20, 0x2, 0x2})
    /home/.../go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000180000)
    /home/.../go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0xc000164000?)
    /home/.../go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x13
main.main()
    /home/.../go/pkg/mod/github.com/mworzala/mc@v0.1.1/main.go:41 +0x112
```

**Comment by mworzala** [comment]
Was a corrupted file during failed download (fixed in https://github.com/mworzala/mc/commit/e84d54ee2401c8390b5684bc3d0dab838a2532c2) but the error logs were not sent to terminal (fixed in https://github.com/mworzala/mc/commit/bc888962477fa6228e02182d072484205b1a6849)
